import Head from 'next/head'
import { Inter } from 'next/font/google'
import Navbar from '@/components/navbar'
import HeroSection from '@/components/hero'
import CoreSection from '@/components/core-section'
import CloudSection from '@/components/cloud-section'
import ClientSection from '@/components/clients-section'
import WhatsNew from '@/components/whats-new-section'
import WhyPrefect from '@/components/why-prefect'


export default function Home() {
  return (
    <div className='m-auto'>
      <Head>
        <title>Prefect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection/>
      <CoreSection/>
      <CloudSection/>
      <ClientSection/>
      <WhatsNew/>
      <WhyPrefect/>
    </div>
  )
}
